version: '3'
services:
  mongo:
    image: mongo:3.6
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27019:27017"

  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data/db
    ports:
      - "6379:6379"
    expose:
    - "6379"
    command: ["redis-server", "--appendonly", "yes"]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always

  ec-demo:
    build: .
    container_name: media.ec-demo
    command: bash -c "tail -f /dev/null"
    volumes:
      - .:/usr/ec-demo
      - /usr/ec-demo/node_modules
    ports:
      - "3009:3009"
      - "3010:3010"
    
